"""Initial schema setup

Revision ID: 7471c00fe2b8
Revises: 
Create Date: 2026-07-01 22:46:49.918628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7471c00fe2b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publishing_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('post_id', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['instagram_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishing_logs_id'), 'publishing_logs', ['id'], unique=False)
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_users_email'), table_name='users_old')
    op.drop_index(op.f('ix_users_id'), table_name='users_old')
    op.drop_index(op.f('ix_users_mobile_number'), table_name='users_old')
    op.drop_index(op.f('ix_users_username'), table_name='users_old')
    op.drop_table('users_old')
    op.drop_index(op.f('ix_post_accounts_id'), table_name='post_accounts')
    op.drop_table('post_accounts')
    op.drop_index(op.f('ix_credential_update_requests_id'), table_name='credential_update_requests')
    op.drop_table('credential_update_requests')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_username'), table_name='accounts')
    op.drop_table('accounts')
    op.add_column('instagram_accounts', sa.Column('facebook_user_id', sa.String(), nullable=True))
    op.add_column('instagram_accounts', sa.Column('facebook_page_name', sa.String(), nullable=True))
    op.add_column('instagram_accounts', sa.Column('page_access_token', sa.Text(), nullable=False))
    op.add_column('instagram_accounts', sa.Column('instagram_business_id', sa.String(), nullable=True))
    op.add_column('instagram_accounts', sa.Column('instagram_username', sa.String(), nullable=True))
    op.add_column('instagram_accounts', sa.Column('token_expiry', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'instagram_accounts', ['instagram_business_id'])
    op.drop_constraint(None, 'instagram_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'instagram_accounts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('instagram_accounts', 'last_login_status')
    op.drop_column('instagram_accounts', 'last_publish_status')
    op.drop_column('instagram_accounts', 'instagram_account_id')
    op.drop_column('instagram_accounts', 'encrypted_password')
    op.drop_column('instagram_accounts', 'token_expiry_time')
    op.drop_column('instagram_accounts', 'encrypted_access_token')
    op.drop_column('instagram_accounts', 'instagram_username_or_email')
    op.drop_constraint(None, 'logs', type_='foreignkey')
    op.create_foreign_key(None, 'logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_mobile_number'), 'users', ['mobile_number'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_mobile_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_constraint(None, 'logs', type_='foreignkey')
    op.create_foreign_key(None, 'logs', 'users_old', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('instagram_accounts', sa.Column('instagram_username_or_email', sa.VARCHAR(), nullable=False))
    op.add_column('instagram_accounts', sa.Column('encrypted_access_token', sa.TEXT(), nullable=True))
    op.add_column('instagram_accounts', sa.Column('token_expiry_time', sa.DATETIME(), nullable=True))
    op.add_column('instagram_accounts', sa.Column('encrypted_password', sa.TEXT(), nullable=False))
    op.add_column('instagram_accounts', sa.Column('instagram_account_id', sa.VARCHAR(), nullable=True))
    op.add_column('instagram_accounts', sa.Column('last_publish_status', sa.VARCHAR(), nullable=False))
    op.add_column('instagram_accounts', sa.Column('last_login_status', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'instagram_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'instagram_accounts', 'users_old', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'instagram_accounts', type_='unique')
    op.drop_column('instagram_accounts', 'token_expiry')
    op.drop_column('instagram_accounts', 'instagram_username')
    op.drop_column('instagram_accounts', 'instagram_business_id')
    op.drop_column('instagram_accounts', 'page_access_token')
    op.drop_column('instagram_accounts', 'facebook_page_name')
    op.drop_column('instagram_accounts', 'facebook_user_id')
    op.create_table('accounts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('access_token', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_username'), 'accounts', ['username'], unique=1)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_table('credential_update_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('instagram_account_id', sa.INTEGER(), nullable=True),
    sa.Column('requested_username_or_email', sa.VARCHAR(), nullable=False),
    sa.Column('requested_password', sa.VARCHAR(), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('admin_comments', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('requested_access_token', sa.TEXT(), nullable=True),
    sa.Column('facebook_page_id', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users_old.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credential_update_requests_id'), 'credential_update_requests', ['id'], unique=False)
    op.create_table('post_accounts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('account_id', sa.INTEGER(), nullable=False),
    sa.Column('publish_status', sa.VARCHAR(), nullable=False),
    sa.Column('published_at', sa.DATETIME(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_accounts_id'), 'post_accounts', ['id'], unique=False)
    op.create_table('users_old',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('mobile_number', sa.VARCHAR(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('email_verified', sa.BOOLEAN(), nullable=False),
    sa.Column('mobile_verified', sa.BOOLEAN(), nullable=False),
    sa.Column('publishing_permission', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users_old', ['username'], unique=1)
    op.create_index(op.f('ix_users_mobile_number'), 'users_old', ['mobile_number'], unique=1)
    op.create_index(op.f('ix_users_id'), 'users_old', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users_old', ['email'], unique=1)
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('instagram_account_id', sa.INTEGER(), nullable=False),
    sa.Column('media_path', sa.VARCHAR(), nullable=False),
    sa.Column('caption', sa.TEXT(), nullable=True),
    sa.Column('hashtags', sa.TEXT(), nullable=True),
    sa.Column('publish_status', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('failure_reason', sa.TEXT(), nullable=True),
    sa.Column('job_id', sa.VARCHAR(), nullable=True),
    sa.Column('progress_percent', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users_old.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.drop_index(op.f('ix_publishing_logs_id'), table_name='publishing_logs')
    op.drop_table('publishing_logs')
    # ### end Alembic commands ###
